kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv0001-pv
  labels:
    type: ebs-vol
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    fsType: "ext4"
    volumeID: "vol-056a06d20dc0d8ef1"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv0001-pvc-web-dmz
  namespace: web-dmz
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      type: ebs-vol
